version: "3.7"
services:
  postgres:
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_USER=akash
      - POSTGRES_PASSWORD=akash
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    environment:
      - ADMINER_DESIGN=pepa-linha
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  db_data:
    driver: local
